version: "3.8"

x-build: &dockerfile-dev-build
  context: .
  dockerfile: Dockerfile

services:
  db:
    image: postgres:13.2-alpine
    user: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  app:
    build: *dockerfile-dev-build
    ports:
      - 8888:8888
    depends_on:
      - db
    volumes:
      - .:/home/appuser
  builder:
    build: *dockerfile-dev-build
    volumes:
      - .:/home/appuser
    command:
      [
          "./scripts/build-integration-layer.sh"
      ]
